# >> **BASIC SETTINGS**
# Minimal configuration with grid/tiled layout focus
start-at-login = true
after-login-command = []
after-startup-command = []

# >> **LAYOUT CONFIGURATION**
# Set tile-based layout as the default with automatic orientation
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# >> **KEY MAPPING**
[key-mapping]
    preset = 'qwerty'

# >> **WINDOW GAPS**
# Minimal gaps for a cleaner look
[gaps]
    inner.horizontal = 2
    inner.vertical = 2
    outer.left = 2
    outer.bottom = 2
    outer.top = 2
    outer.right = 2

# >> **BASIC KEYBINDINGS**
[mode.main.binding]
    # Essential window management
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'
    
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'
    
    # Layout control - ensure tiled layout
    alt-t = 'layout tiles horizontal vertical'
    
    # Window sizing
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'
    
    # Basic workspace navigation
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    
    # Quick system commands
    alt-q = 'close'
    alt-r = 'reload-config'
    alt-tab = 'workspace-back-and-forth'