#!/usr/bin/env sh

# >> script additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# >> borders
borders active_color=0xff61AFF0 inactive_color=0xff282C34 width=2.0 &

# >> yabai workspaces
function setup_space {
  local idx="$1"
  local name="$2"
  if ! yabai -m query --spaces --space "$idx" >/dev/null 2>&1; then
    yabai -m space --create
  fi
  yabai -m space "$idx" --label "$name"
}

setup_space 1 emacs
setup_space 2 code
setup_space 3 web
setup_space 4 social
setup_space 5 media
# setup_space 6 other

# >> global config
yabai -m config layout bsp

# >> window
yabai -m config window_placement second_child
yabai -m config window_opacity on
yabai -m config window_shadow off
yabai -m config window_animation_duration 0.15
yabai -m config window_opacity_duration 0.15
yabai -m config active_window_opacity 1.0

# >> padding
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# >> split
yabai -m config split_ratio 0.50
yabai -m config split_type auto

# >> mouse
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action warp
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise

# >> desactivate for apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Zoom.us$" manage=off